### ISSUE TITLE
Sampling error - random batch generator

### ISSUE THREAD

**Issue by AnjirHossain** [anooshac/machine-learning-projects#3]
I noticed an error when trying to generate random batches. I was hoping to see if you had any idea how this could be resolved?

`Traceback (most recent call last):
  File "seq2seq_train.py", line 38, in <module>
    sess = model.train(train_batch_gen, val_batch_gen, sess)
  File "/Users/anjirhossain/Desktop/tmp/text-summarizer/seq2seq_wrapper.py", line 146, in train
    self.train_batch(sess, train_set)
  File "/Users/anjirhossain/Desktop/tmp/text-summarizer/seq2seq_wrapper.py", line 101, in train_batch
    batchX, batchY = train_batch_gen.__next__()
  File "/Users/anjirhossain/Desktop/tmp/text-summarizer/data_utils.py", line 21, in generate_random_batch
    sample_idx = sample(list(np.arange(len(x))), config.batch_size)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/random.py", line 318, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative`

After digging around, the suggestions I found were to use sampling with replacement via `random.choice`. I'm not entirely sure if this is a sampling issue or something else?

**Comment by AnjirHossain** [comment]
This issue has already been brought up.
